name: simple_auth
description: Simple Auth is the simplest way to authenticate your users/apis.
version: 2.1.0
homepage: https://github.com/clancey/simple_auth

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  meta: ^1.15.0
  http: ^1.5.0
  crypto: ^3.0.6

dev_dependencies:
  test: ^1.26.3
