name: simple_auth_flutter
description: Simple Auth is the simplest way to authenticate your users/apis. This plugin will securely store tokens/credentials as well as automatically present login UI when needed.
version: 2.1.0
homepage: https://github.com/clancey/simple_auth

publish_to: 'none'

environment:
    sdk: '>=3.2.0 <4.0.0'
    flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  simple_auth:
    path: ../simple_auth

flutter:
  plugin:
    platforms:
      android:
        package: clancey.simpleauth.simpleauthflutter
        pluginClass: SimpleAuthFlutterPlugin
      ios:
        pluginClass: SimpleAuthFlutterPlugin
      macos:
        pluginClass: SimpleAuthFlutterPlugin
      web:
        pluginClass: SimpleAuthFlutterWeb
        fileName: simple_auth_flutter_web.dart

dev_dependencies_overrides:
  simple_auth:
    path: ../simple_auth
