name: simple_auth_generator
description: simple_auth is an http client generator using source_gen and inspired from retrofit and chopper
version: 2.1.0
homepage: https://github.com/clancey/simple_auth

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  simple_auth: ^2.0.10
  analyzer: ^6.5.2
  build: ^2.4.1
  build_config: ^1.1.1
  path: ^1.9.0
  source_gen: ^1.4.0
  logging: ^1.3.0
  code_builder: ^4.10.1
  dart_style: ^2.3.6
  
dev_dependencies:
  test:
  build_runner: ^2.4.9
  build_runner_core: ^7.3.1
  build_test: ^2.2.2
  build_verify: ^3.1.0

dev_dependency_overrides:
  simple_auth:
    path: ../simple_auth